import = ["~/.config/alacritty/themes/themes/doom_one.toml"]

[font]
size = 12.0

[font.bold]
family = "JuliaMono"
style = "Bold"

[font.bold_italic]
family = "JuliaMono"
style = "Bold Italic"

[font.italic]
family = "JuliaMono"
style = "Italic"

[font.normal]
family = "JuliaMono"
style = "Regular"